runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: main.app
- url: /stylesheets
  static_dir: stylesheets
- url: /js
  static_dir: js

libraries:
- name: jinja2
  version: latest
- name: webapp2
  version: "2.5.2"
